### PR TITLE
Post Excerpt Functionality

### PR DESCRIPTION
**Pull request by amacgregor**
Hi Nate, 

I made a mess with my previous pull request attempts so I deleted my forked repo and started from scratch. This time the pull request for the excerpt functionality is clean.

To use it just add the  tag anywhere in your content where you want to have the break. I'm working on a few other things:
- Tags
- Adding the epic editor to the backend http://oscargodson.github.com/EpicEditor/
- Adding Rainbow.js for code highligthing

Let me know what you think.

Cheers!

### CODE REVIEW

**Comment by natew** [comment]
I'm actually working on a complete rewrite of obtvse right now.  It's coming along (maybe 75% to a initial release).

It already has a nice markdown live-preview thing thats really slick.   I had been working on a backend based code highlighting system and still am but I had originally tried Rainbow.  I may go back to it if I can't get it working:

https://github.com/tmm1/pygments.rb/issues/18

I even tried using linguist to detect the language, but am not sure how to just pass it the straight code and get back the code-type.  It's a tricky problem and I wish you could set the language of a code block in markdown easily, I think that is our best option.

I've switched to using redcarpet so that may help.

I'll push up an alpha version of it soon.

**Comment by amacgregor** [comment]
Pretty cool, why did you decided to rewrite obtvse ?

**Comment by natew** [comment]
Well, probably mis-spoke.  Less of a re-write and more of a really big change.  You won't need to migrate anything and I didn't start from scratch but it is quite a bit different.

Javascript went from ~120LOC to ~700 and counting :) (and not from feature bloat!  ajax-ified interface and adding polish all around)

**Comment by amacgregor** [comment]
That's awesome. So pulling the changes to my current install should be easy to do ?

**Comment by amacgregor** [comment]
Hey Nate,

Wondering how is the new version coming along ?

**Comment by natew** [comment]
New versions coming along, much closer now but still have bugs and a few things to do.  The biggest being implementing "history" because with auto-save you need a way to edit live articles without them live-updating which requires a new model (Revision) to store the post content and version_number and then tracking it with Post.published_version.  Once that and the last bugs are squashed I'll push it.

 I've shifted focus the last few days to another project but hope to have it ready in the next two weeks.

Haven't tested this but is it working properly with the latest?  If so I'll just go ahead and merge through github, I think it's an important feature and well implemented.

**Comment by cobyism** [comment]
I implemented this slightly differently on my install—by putting the splitting logic into the model and then just calling `post.excerpt` instead of `post.content` depending on which context the partial is in. I also added a 'read more' button below the cutoff on posts with excerpts in the index view.

[Here's the diff for my implementation](https://github.com/cobyism/obtvse/commit/7d1981e7096979c08eb641bf42628c00a7a55ef7) in case you want to use any of it. Let me know if you want it as a pull request.

**Comment by cobyism** [comment]
Up-to-date comparison with another small change: https://github.com/cobyism/obtvse/compare/excerpts

**Comment by amacgregor** [comment]
Hey Coby,

I'll like your changes, I'll give it a try.

**Comment by mindscratch** [comment]
@NateW for language specific code blocks in markdown you can take the github style such as triple single quotes followed by a language such as: ```ruby

then end it with triple single quotes. If you use redcarpet you can get it to convert that markdown into code with a CSS class of "ruby", check out my question on [stackoverflow](http://stackoverflow.com/questions/9694235/how-can-i-convert-github-flavored-markdown-to-html)...although you'd have to have CSS to make it actually look nice.

**Comment by ghost** [comment]
Hey @NateW, 

Hope you are doing well.  How's the big update coming along?  Has it been released yet?  Sorry, a bit behind on things.

**Comment by natew** [comment]
@cobyism Would prefer it in the model, but your diff is 404ing, mind doing a pull request?

@mindscratch Thanks for that, really glad to hear as I was hoping that would be the solution

@CDainMiller Big update is available on the refresh branch right now.

**Comment by cobyism** [comment]
@NateW Woops! I recently changed usernames, so that's why it was 404ing. Updated URL in the comment above, and here's the link again for convenience: https://github.com/cobyism/obtvse/compare/excerpts

**Comment by cobyism** [comment]
... and just sent [a pull request](https://github.com/NateW/obtvse/pull/75) for my version with excerpts in the model :)

**Comment by natew** [comment]
Haha I think I merged it before you pull request came through.

**Pull request closed without merging**
