### PR TITLE
Merge outstanding conflicts in application_helper.rb

### PR DESCRIPTION
**Pull request by cobyism**
Looks like there was a conflict that didn't get resolved.

### CODE REVIEW

**Comment by cobyism** [comment]
Some of the commits above also are from https://github.com/NateW/obtvse/pull/64 to make the README consistent with the codebase concerning `config.yml`.

**Comment by cobyism** [comment]
Hold up... what's doing the markdown conversion here? That redcarpet line was broken, but I'm presuming that's a recent change as it was part of the unmerged conflict from before. With it commented out the app works again, but markdown doesn't get parsed. Did I miss something here?

**Comment by NickWoodhams** [comment]
There are git headers in the file. No bueno.

**Comment by natew** [comment]
I've just gone ahead and cleaned this up myself, should have been paying attention, sorry about that.

**Comment by NickWoodhams** [comment]
No big deal

Appreciate it

On Thu, Apr 26, 2012 at 11:24 AM, nwienert <
reply@reply.github.com

**Comment by cobyism** [comment]
Awesome. Thanks @natew! Sorry for my confused pull-request lol.

**Pull request closed without merging**
