### PR TITLE
Heroku config

### PR DESCRIPTION
**Pull request by mduvall**
Since the aim seems to be to support an easier deployment via Heroku I added two lines that pull out two variables out of ENV for login and password. The user can set these via `heroku config:add blog_login=<BLOG_LOGIN> blog_password=<BLOG_PASSWORD>` and it will persist between deployments, then fall back to 'username' and 'password' locally or if it is not set.

Thoughts?

### CODE REVIEW

**Comment by natew** [comment]
Not really sure about this as it may confuse non-heroku people, does config.yml not persist between deployments normally?

Perhaps just add this to the docs as an alternative option.

**Comment by mduvall** [comment]
That is a valid concern, the main benefit here is not the deployment persistence but the good practice of separating the configuration environment (whether it's local or on Heroku, or some other service) from the repository.

This would make it easier for people to maintain their own forks without having to worry about adding their config.yml to their .gitignore or some other means to make sure that their credentials do not end up on their repository on GitHub. I could comment out the current lines as a way for the user to easily access a solution, much in the way that the standard routes.rb is configured out of the box. What do you think?

**Comment by usmanity** [comment]
:+1:

**Comment by jakeonrails** [comment]
@maskact I would suggest making all of those configs optional environment variables, and prefix them with OBTVSE_ instead of BLOG_.

:+1: When I got set to push to heroku this was my first thought - that I didn't want to clone and publish my config.yml via github so my clone is in a private repo for now. I'd much rather have it public! :)

**Pull request merged**
