### PR TITLE
Ruby187compat

### PR DESCRIPTION
**Pull request by sshandilya**
Fixed stuff to work on ruby v1.8.7 as tested on OSX Lion.

### CODE REVIEW

**Comment by krainboltgreene** [comment]
I disagree with making it 1.8 compatible. Ruby is moving to 1.9 and 2.0, there's no real reason you would want to use 1.8.

**Comment by krainboltgreene** [comment]
Also, maybe you should move the http change to a different pr?

**Comment by ethnt** [comment]
I agree with @krainboltgreene, the Ruby community needs to move away from 1.8.7. 1.9.\* is already pretty stable, I don't see a reason to stick with 1.8.7.

**Comment by krainboltgreene** [comment]
Looks like there are already commits switching it from 1.9 hash syntax to 1.8, as well as adding a lot of Rubymine files: 6a7194b7a02cf8313e3a2bd1a5b95c39ad37f3e8

:thumbsdown:

**Comment by natew** [comment]
I agree with 1.9.  If someone wants to make a pull request with 1.9, I'll add it to the install documentation as well.

**Comment by sshandilya** [comment]
Agree with all of the above! I just made the changes to make obtvse run on the stock ruby that comes with OSX Lion, which sadly is still 1.8.7. Apple needs to get its act together and move over to 1.9.\* :lock: :apple: :lock:

**Pull request closed without merging**
