### PR TITLE
Fixed a typo in README.md

### PR DESCRIPTION
**Pull request by tdcook**
The line in README.md containing examples of the config environment variables contained a typo. The "w" and "o" in "password" were transposed.

### CODE REVIEW

**Comment by fuxihua** [comment]
When I command 'git push heroku master', there is a following error.
"Enter passphrase for key '/c/Documents and Settings/Administrator/.ssh/id_rsa':
 !  Your key with fingerprint bf:04:12:f7:0e:40:ae:29:ba:2d:8e:49:5d:1a:4a:a2 is not authorized to access obtvse.
fatal: The remote end hung up unexpectedly
"
How to resolve it?

**Comment by tjstein** [comment]
This is an issue with your SSH keys, not obtvse. You have to upload your public key to Heroku:

$ heroku keys:add ~/.ssh/id_rsa.pub

**Comment by fuxihua** [comment]
I try the command which you suggested. But it still failed.

**Comment by tdcook** [comment]
From the looks of it you are on Windows, so the command will probably look something like this:

heroku keys:add "C:\Documents and Settings\Administrator\.ssh\id_rsa.pub"

Also keep in mind this comment section is really meant for this specific pull request so you might not get much help here.

**Pull request merged**
